### ISSUE TITLE
Do we still need SceneRenderer.AccumulateLight?

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#117]
If so, the implementation needs to be changed. It's not a good idea to start a Viserator scene traversal over the entire scene from an already on-going traversal whenever a light component is hit. See[ this code line](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/SceneRenderer.cs#L837).

**Comment by RedImp1470** [comment]
In the multipass branch lights are collected in Render() before the traversal is started (see [this code line](https://github.com/FUSEEProjectTeam/Fusee/blob/38cabe73fa2a678edf5e472e0f286c2a79d6c394/src/Engine/Core/SceneRendererForward.cs#L293)) . Therefor this should be fixed in develop with the next merge from multipass.
