### ISSUE TITLE
Point cloud rendering: WPF/GLFW multithreading error

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#305]
When opening a file for the second time we get the following error:

_OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: 'Can only create windows on the Glfw main thread. (Thread from which Glfw was first created).'_

Calling GLFW.Terminate at the end of Run() does not seem to help.

**Comment by wrestledBearOnce** [comment]
This could be a problem with the [`SynchronizationContext`](https://hamidmosalla.com/2018/06/24/what-is-synchronizationcontext/). 
Inside the WebAsm branch one can find this class:

https://github.com/FUSEEProjectTeam/Fusee/blob/develop_wasm/src/Engine/Imp/Graphics/Desktop/DesktopRenderCanvasImpContext.cs

which should force the main thread to return to its' initial thread after every async or external method call. Otherwise it can happen that an async method is being run upon thread nbr. 3 and our main thread--upon completion-- just stays there instead of returning to it's initial thread nbr. 0.

WPF and WinForms do provide their own `SynchronizationContext` for this reason but for our use case I needed to implement it "by hand". You could try to cherry pick this class which should work straight away, as it inherits the base class `SynchronizationContext` and C# provides some magic behind the curtain.

**Comment by griestopf** [comment]
Issue is solved
