### ISSUE TITLE
Minimizing the window destroys the scene

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#334]
Steps to reproduce:

- Launch any project
- Minimize it via "minimize" window button
- Restore it 
- Window is blank
- Use mouse navigation and the scene should pop back up
- Enjoy your unlit scene and missing GUI

Furthermore:
PC-Rendering example throws an "incomplete framebuffer" exception when minimized

![image](https://user-images.githubusercontent.com/4386896/131836534-f9e46dd1-f623-4e53-b9bd-ad36b53aadb3.png)

**Comment by ASPePeX** [comment]
My first guess is that something breaks because minimizing the window calls Resize with width/height of zero.

**Comment by ASPePeX** [comment]
Catching a w/h of zero in resize and forcing it to one avoids this bug. But I think it should be fixed in a more appropriate place.

**Comment by ASPePeX** [comment]
Another quick fix is just returning from `RenderAFrame` when Width or Height is zero. But this is also not necessarily what we want since this is basically halting all user code.

Imo a way to cleanly fix it from the engine-side is implementing #194 and using this fix engine-side, not calling `OnRenderFrame` when Width or Height is zero. So if the user is using `OnUpdateFrame` und `OnRenderFrame` correctly  all rendering is halted but whatever they still want to do (simulations, network, etc.) can still be handled in `OnUpdateFrame`.


```
        public override void RenderAFrame()
        {
            if (Height == 0 || Width == 0)
                return;

            [..]
        }
```
