### ISSUE TITLE
Input.Mouse broken, velocity calculation does not work

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#492]
After splitting `Render()` and `Update()` one needs to calculate mouse velocity inside https://github.com/FUSEEProjectTeam/Fusee/blob/b646b8732c0bab98992d8f69eea0e91d3490aa52/src/Engine/Core/InputDevice.cs#L817 and https://github.com/FUSEEProjectTeam/Fusee/blob/b646b8732c0bab98992d8f69eea0e91d3490aa52/src/Engine/Core/InputDevice.cs#L822 with `Time.DeltaTimeUpdate` and not with `Time.DeltaTime` anymore. This should fix this #425 bug. 

However, in doing so, the calculation of the mouse velocity fails every so often, resulting in an 'overshooting' of values and a broken mouse look. This should be addressed immediately as mouse input fails inside the `PointCloudExample` when `Time.DeltaTime` values are getting too big, resulting in a mouse velocity of `0`

Possible quick fix: Set `_gameWindow.UpdateFrequency = 0`

**Comment by wrestledBearOnce** [comment]
For reference:

This is how `OpenTK` dispatches calls to `Update()`, this breaks our input.
From `OpenTK.Windowing.Desktop.GameWindow`

```csharp
private double DispatchUpdateFrame()
        {
            int num = 4;
            double totalSeconds = _watchUpdate.Elapsed.TotalSeconds;
            double num2 = (UpdateFrequency == 0.0) ? 0.0 : (1.0 / UpdateFrequency);
            while (totalSeconds > 0.0 && totalSeconds + _updateEpsilon >= num2)
            {
                ProcessInputEvents();
                NativeWindow.ProcessWindowEvents(base.IsEventDriven);
                _watchUpdate.Restart();
                UpdateTime = totalSeconds;
                OnUpdateFrame(new FrameEventArgs(totalSeconds));
                _updateEpsilon += totalSeconds - num2;
                if (UpdateFrequency <= double.Epsilon)
                {
                    break;
                }

                IsRunningSlowly = (_updateEpsilon >= num2);
                if (IsRunningSlowly && --num == 0)
                {
                    _updateEpsilon = 0.0;
                    break;
                }

                totalSeconds = _watchUpdate.Elapsed.TotalSeconds;
            }

            if (UpdateFrequency != 0.0)
            {
                return num2 - totalSeconds;
            }

            return 0.0;
        }
```

**Comment by ASPePeX** [comment]
> Possible quick fix: Set `_gameWindow.UpdateFrequency = 0`

Quick fix probably, because it will behave exactly like `RenderAFrame()`. But the only reason to have `Update()` is to have a fixed update frequency. We can do that but the actual fix could be quicker.

I just noticed the calls to `Input.Instance.PreRender()` and `Input.Instance.PostRender()`, which actually call the code you mentioned, are only called by `RenderAFrame()`. I think changing `PreRender()` to `PreRender(float deltaTime)` and calling them in `Update()` and `RenderAFrame()` would solve the mouse problem.
But it would probably introduce bugs with the button down state, especially if we also double up `PostRender()`.

https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/RenderCanvas.cs#L197L221

On a quick glance I only see few possibilities of fixing it entirely.
 1. Implement the Render/Update cycle ourselves.
 2. Confine Inputs entirely to the Update loop.
 3. Make the inputs states entirely event based.
with 2. being the quickest fix, while changing to 3. in the future.

**Comment by wrestledBearOnce** [comment]
> I just noticed the calls to Input.Instance.PreRender() and Input.Instance.PostRender(), which actually call the code you mentioned, are only called by RenderAFrame(). 

Oh, missed this completely. Let's discuss the solutions in our next meeting. I think we should implement `2.` with our next release, followed by `3.` later this year. Right now @RedImp1470 is using the quick fix with `UpdateFreq = 0` and passing `DeltaTimeUpdate` instead of `DeltaTime` to `PreRender()` which restores/fixes mouse velocity inside the point cloud example.

**Comment by wrestledBearOnce** [comment]
I went ahead and implemented `2.` as a hotfix
