### ISSUE TITLE
Fusee.Test.Render.Desktop: cannot spawn the (glfw) game window due to xunit executing the test in another thread

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#504]
Debugging the test will lead to:
_"OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: 'GLFW can only be called from the main thread!'"_

XUnit seems to execute the test in another thread then the main thread.

![image](https://user-images.githubusercontent.com/9215439/170949906-b1572cec-50a4-4e2c-8c91-8252349f21ac.png)

Running the [OpenTk Integration/Window tests](https://github.com/opentk/opentk/blob/master/tests/OpenTK.Tests.Integration/GameWindowTests.fs) seem to lead to the same error.

Used OpenTK Version: 4.7.2

**Comment by wrestledBearOnce** [comment]
"Fixed" RenderTests with bd2a6060c56551307204613265f294a217e95198

Moved from xUnit to nunit. Generate all images in main method before any tests are being evaluated.

Start console app instead of test runner. The thread spawning is a Visual Studio behavior.

Somehow the generated images are a bit "strange". 

@RedImp1470 your input is needed 😉 


![SimpleTest](https://user-images.githubusercontent.com/4386896/175616063-71d70508-7145-4922-baaf-60e4079bc451.png)
