### ISSUE TITLE
Reopening the same Potree file doesn't work

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#736]
Using these methods fails: 

https://github.com/FUSEEProjectTeam/Fusee/blob/e2ceecc95bf66651d1ded54de74a9fbc115a60a4/Examples/Complete/PointCloudPotree2/Core/PointCloudPotree2Core.cs#L55

due to recent changes to the `PotreeReader` 

e. g. `static Dictionary<FileInfo, PotreeData>` in `PotreeReader()`

**Comment by ASPePeX** [comment]
Currently a Potree-file that is loaded in a `PotreeData` class that is in use by a `Potree2Reader` or `Potree2Writer` cannot be loaded again due to the file still being locked by the fille access from the `MemoryMappedFile`.

Disposing `PotreeData` will silently fail while there are still references to its `MemoryMappedViewAccessor`, which are currently held in `Potree2Reader`/`Potree2Writer`. Thus the quick user fix for this is to dispose of any `Potree2Reader`/`Potree2Writer` that is currently holding a reference to `PotreeData`.

A propper fix for this is to move the `MemoryMappedViewAccessor`s to `PotreeData` and add them to `PotreeData`s Dispose.
