### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#96]
- [x] Develop concept
- [x] Implementation

**Comment by RedImp1470** [comment]
Implementation ideas:

1. CameraComponent sets the projection matrix (like the ProjectionComponent does now).
2. TransformComponent sets the view matrix.
3. View and projection matrices should not be public and settable from user code anymore.
4. Viewport width and height should not be public in the CameraComponent like they are in the ProjectionComponent at the moment.
5. Support multiple cameras
5.1 One camera per rendered viewport -- assign camera to viewport somehow.
5.2 Camera should have a "active" and/or "main camera" flag.

**Comment by griestopf** [comment]
- (3) View and projection matrices **should stay** public and settable from user code. A Node should save the current view and projection state and restore it after the `Children` list was traversed. FUSEE Applications should work without scene graphs/scene renderers.

- (1) & (2) YES! 

Implementation details: 
- Implement a `CameraComponent` containing the following properties
```C# 
  var ProjectionType // Perspective or Ortho
  bool Active;
  float4 Viewport; // Relative 
  float Fov; // Vertical
  float Near;
  float Far;
  Writable RenderTexture;
  event CustomCameraUpdate CustomCameraUpdateEvent;
```
- On Rendering an accumlation traversal collects all active cameras
- For each active camera
  - if RenderTexture is given set it as the current render target on the RC
  - if CustomCameraUpdateEvent is set, call the event to yield projection and absolute viewport settings. Otherwise calculate projection matrix and absolute viewport based on the above properties.
  - Render the scene graph (forward or deferred)
- Remove current ProjectionComponent visit method.
